apiVersion: apps/v1
kind: Deployment 
metadata:
  name: project-dep
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: project-app
  template:
    metadata:
      name: project-pod
      labels: 
        app: project-app
    spec:
      containers:
        - name: project-container
          image: ramguguloth/djangoapp:v1
          ports:
            - containerPort: 8000