apiVersion: v1
kind: Service 
metadata:
  name: project-lb
  labels:
    app: project-app
spec:
  type: LoadBalancer
  selector:
    app: project-app
  ports: 
    - name: http 
      port: 8000
      targetPort: 8000